name: BuildWebGL

on:
  push:
    branches:
    - master

jobs:
  
  ReportJob:
    runs-on: ubuntu-latest
    #needs: PushJob
    steps:
    - run: curl https://discordapp.com/api/webhooks/631669163525668894/E1qFbhGKeD9fYNBx85S4UvcuOa3qFowMlunSByJCMEN6-tdiM6CF3YrKIeid5h9A6Jpi -X POST -H "Content-Type:application/json" -d "{\"content\":\"Build Complete!\\nCheck Repository!\"}"